### PR TITLE
Update refund rate lower bound in gas reserve

### LINKED ISSUE #39: Refund should have a minimum value
https://github.com/QuarkChain/quarkchain-contracts/blob/28936b2b4ed46379550e61413da7aad31021989e/contracts/GeneralNativeTokenManager.sol#L113

Such as 10%.

This prevents a bidder submitting a bid and then refund most of the QKC via a large gas transaction with a negligible cost.

### PR DESCRIPTION
**Pull request by ninjaahhh**
resolves #39

### CODE REVIEW

**Comment by ninjaahhh** [comment]
> I think we could also make it changeable by the supervisor.

do we really want to do that? it means token admins somehow need to trust the supervisor more

**Comment by qizhou** [comment]
The supervisor can be a DAO, but I think we need a way to set the lower limit to 10 or others if necessary.

**Comment by qizhou** [comment]
BTW: we may also need a method to set the initial value of the refund rate (rather than 50%)

**Comment by ninjaahhh** [comment]
updating lower bound or initial value won't work proactively and adds extra complexity to the contract. considering the use case we are facing is relative rare (i.e. exchanges rates are different between shards), I think we should make the refund process as simple as possible:

1. either have a hard-coded refund rate (or even bake it into the consensus), or
2. like current process which allows admins to configure the refund rate within sane defaults

**Pull request merged**
